require:
  - standard

# Omakase Ruby styling for Rails
inherit_gem: { standard: config/base.yml, rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
